In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# df=pd.read_csv('movies_metadata.csv')
df = pd.read_csv('movies_metadata.csv', engine='python')
# import pandas as pd

# df = pd.read_csv(
#     'movies_metadata.csv',
#     engine='python',
#     on_bad_lines='skip',
#     encoding='utf-8'
# )

In [ ]:
df.head()
# adult----	Movie adult (18+) hai ya normal
# belongs_to_collection----	Movie kisi series ka part hai ya nahi (jaise Avengers collection)
# budget----	Movie banane me kitna paisa laga
# genres----	Movie kis type ki hai – Action, Comedy, Drama etc
# homepage----	Movie ki official website
# id-----	Movie ka unique number (database me)
# imdb_id----	IMDB website ka movie ID
# original_language	----Movie ki asli language (en, hi, fr etc)
# original_title----	Movie ka original naam
# overview---	Movie ka short summary / story
# popularity-----	Movie kitni famous hai
# poster_path	----Movie poster ki image location
# production_companies----	Kaunsi company ne movie banayi
# production_countries-----	Kaunse country me movie bani
# release_date-----	Movie kab release hui
# revenue	-----Movie ne kitna paisa kamaya
# runtime----	Movie ki length (minutes me)
# spoken_languages----	Movie me kaun-kaun si language boli gayi
# status-----	Movie release hui ya upcoming
# tagline-----	Movie ka chota slogan
# title	---Movie ka common name
# video	Trailer--- video available hai ya nahi
# vote_average----	Audience rating (0–10 scale)
# vote_count------	Kitne logon ne vote diya

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df.shape

(14171, 24)

In [ ]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
df.isnull().sum()

adult                        0
belongs_to_collection    12273
budget                       0
genres                       0
homepage                 12591
id                           0
imdb_id                      3
original_language            0
original_title               0
overview                    52
popularity                   0
poster_path                 41
production_companies         0
production_countries         0
release_date                 6
revenue                      0
runtime                     10
spoken_languages             0
status                      10
tagline                   5009
title                        1
video                        1
vote_average                 1
vote_count                   1
dtype: int64

In [ ]:
df=df.drop_duplicates().reset_index(drop=True)#removed null columns

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df=df[['title','overview','genres','tagline','vote_average','popularity']]

In [ ]:
df.isnull().sum()#bahut sari value hai jisme null value hai unko htana pdega(title to seedha htao kuki name hi ni pta to search kese hoga)

title              1
overview          52
genres             0
tagline         5008
vote_average       1
popularity         0
dtype: int64

In [ ]:
df=df.dropna(subset=['title'])#null value delete krdi

In [ ]:
df['overview']=df['overview'].fillna('') #null value ki jagah empty spes bhar diya

In [ ]:
df.iloc[0]['genres']#fist row ka gernre dekha

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [ ]:
import ast
df['genres']=df['genres'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]))#ak bar yeh line chatgpt kre.

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [ ]:
df['tagline']=df['tagline'].fillna('')

In [ ]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [ ]:
#combine=title,overvier,gernes
df['tags']=df['title']+" "+df['overview']+" "+df['genres']

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Toy Story Led by Woody, Andy's toys live happi..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,Jumanji When siblings Judy and Peter discover ...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900,Grumpier Old Men A family wedding reignites th...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Waiting to Exhale Cheated on, mistreated and s..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Father of the Bride Part II Just when George B...

NLP:-Text Preprocessing

In [ ]:
#convert tag to some number.
df['tags'][1]

"Jumanji When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family"

In [ ]:
df['tags'][0]

"Toy Story Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family"

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words=set(stopwords.words('english'))
lemmatizer=nltk.WordNetLemmatizer()

In [ ]:
def preprocess_text(text):
  text=str(text).lower()
  #remove pantuation
  text=re.sub(r'[^a-zA-Z\s]','',text)
  words=text.split()#word tokenisation
  words=[word for word in words if word not in stop_words]#remove stop words
  #lemmatize
  words=[lemmatizer.lemmatize(word) for word in words]
  return " ".join(words)

In [ ]:
df['tags']=df['tags'].apply(preprocess_text)

Jumanji When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family

In [ ]:
df['tags'][1]

'jumanji sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family'

In [ ]:
df=df.reset_index(drop=True)

In [ ]:
indices=pd.Series(df.index,index=df['title']).drop_duplicates()

In [ ]:
indices

title
Toy Story                                0
Jumanji                                  1
Grumpier Old Men                         2
Waiting to Exhale                        3
Father of the Bride Part II              4
                                     ...
The Final Destination                14161
Gamer                                14162
Cloudy with a Chance of Meatballs    14163
Radio Inside                         14164
I Can Do Bad All By Myself           14165
Length: 14166, dtype: int64

TFIDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf=TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [ ]:
tfidf_metrix=tfidf.fit_transform(df['tags'])#all tag change in vetrix

In [ ]:
tfidf_metrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 509837 stored elements and shape (14166, 50000)>

COSINE SIMILARITYYYYY

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(title,n=10):
  if title not in indices:
    return ["🎬movie not found❌"]

  idx=indices[title]
  sim_score=cosine_similarity(tfidf_metrix[idx],tfidf_metrix).flatten()
  similar_idx=sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [ ]:
recommend('Toy Story')

2996                Toy Story 2
2141                       Toys
11396    For Your Consideration
1071      Rebel Without a Cause
1931                  Condorman
485                      Malice
1810             Small Soldiers
1032              The Sunchaser
10937                  The Wild
7253             Africa Screams
Name: title, dtype: object

In [49]:
import pickle
df['title'] = df['title'].str.lower()
indices = pd.Series(df.index, index=df['title'])

pickle.dump(tfidf_metrix,open('tfidf_metrix.pkl','wb'))

In [50]:
pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(recommend,open('tfidf.pkl','wb'))